apiVersion: v1
kind: Service
metadata:
  name: user-service-external
  namespace: kong
  labels:
    app.kubernetes.io/name: user-service-external
spec:
  type: ExternalName
  externalName: user-service.default.svc.cluster.local
  ports:
  - port: 8000
    targetPort: 8000