apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-jwt
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
    konghq.com/credential-type: jwt
type: Opaque
data:
  jwt-secret: {{ .Values.jwt.secret | b64enc }}