apiVersion: v2
name: waf-nginx
description: NGINX Ingress Controller with ModSecurity WAF
type: application
version: 0.1.0
appVersion: "1.9.0"
dependencies:
  - name: ingress-nginx
    version: "4.8.0"
    repository: "https://kubernetes.github.io/ingress-nginx"